df <- read.csv("data/hotel_bookings.csv")

# Dictionnaire des variables initiales de la base.
# La colonne Choix indique si la variable est retenue directement ou comme
# source d'une variable construite pour l'analyse et la modélisation.
dico_variables <- data.frame(
  "Nom de la variable" = c(
    "hotel",
    "is_canceled",
    "lead_time",
    "arrival_date_year",
    "arrival_date_month",
    "arrival_date_week_number",
    "arrival_date_day_of_month",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adults",
    "children",
    "babies",
    "meal",
    "country",
    "market_segment",
    "distribution_channel",
    "is_repeated_guest",
    "previous_cancellations",
    "previous_bookings_not_canceled",
    "reserved_room_type",
    "assigned_room_type",
    "booking_changes",
    "deposit_type",
    "agent",
    "company",
    "days_in_waiting_list",
    "customer_type",
    "adr",
    "required_car_parking_spaces",
    "total_of_special_requests",
    "reservation_status",
    "reservation_status_date"
  ),
  "Description" = c(
    "Type d'hôtel concerné par la réservation : Resort Hotel ou City Hotel.",
    "Variable cible indiquant si la réservation a été annulée : 1 = annulée, 0 = non annulée.",
    "Nombre de jours entre la date de réservation et la date d'arrivée prévue.",
    "Année d'arrivée prévue du client.",
    "Mois d'arrivée prévue du client.",
    "Numéro de semaine de l'année correspondant à l'arrivée prévue.",
    "Jour du mois correspondant à l'arrivée prévue.",
    "Nombre de nuits de week-end réservées.",
    "Nombre de nuits en semaine réservées.",
    "Nombre d'adultes associés à la réservation.",
    "Nombre d'enfants associés à la réservation.",
    "Nombre de bébés associés à la réservation.",
    "Type de repas réservé.",
    "Pays d'origine du client, code selon la nomenclature pays disponible dans la base.",
    "Segment de marché ou canal commercial à l'origine de la réservation.",
    "Canal de distribution utilisé pour effectuer la réservation.",
    "Indique si le client est déjà venu auparavant : 1 = oui, 0 = non.",
    "Nombre d'annulations précédentes effectuées par le client.",
    "Nombre de réservations précédentes non annulées par le client.",
    "Type de chambre initialement réservée.",
    "Type de chambre finalement attribuée.",
    "Nombre de modifications effectuées sur la réservation.",
    "Type de dépôt ou garantie associé à la réservation.",
    "Identifiant de l'agence de voyage ayant effectué la réservation, si applicable.",
    "Identifiant de l'entreprise associée à la réservation, si applicable.",
    "Nombre de jours passés sur liste d'attente avant confirmation.",
    "Type de client : Transient, Contract, Group ou Transient-Party.",
    "Prix moyen journalier de la réservation.",
    "Nombre de places de parking demandées par le client.",
    "Nombre de demandes spéciales formulées par le client.",
    "Statut final de la réservation : annulée, non annulée ou no-show.",
    "Date du dernier statut de la réservation."
  ),
  "Type" = c(
    "Qualitative",
    "Qualitative",
    "Quantitative",
    "Quantitative",
    "Qualitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Qualitative",
    "Qualitative",
    "Qualitative",
    "Qualitative",
    "Qualitative",
    "Quantitative",
    "Quantitative",
    "Qualitative",
    "Qualitative",
    "Quantitative",
    "Qualitative",
    "Qualitative",
    "Qualitative",
    "Quantitative",
    "Qualitative",
    "Quantitative",
    "Quantitative",
    "Quantitative",
    "Qualitative",
    "Date"
  ),
  "Choix" = c(
    "Retenue",
    "Retenue",
    "Retenue",
    "Non retenue",
    "Retenue",
    "Non retenue",
    "Non retenue",
    "Retenue",
    "Retenue",
    "Retenue",
    "Retenue",
    "Retenue",
    "Non retenue",
    "Retenue",
    "Retenue",
    "Non retenue",
    "Retenue",
    "Retenue",
    "Non retenue",
    "Non retenue",
    "Non retenue",
    "Retenue",
    
    "Retenue",
    "Non retenue",
    "Non retenue",
    "Non retenue",
    "Retenue",
    "Retenue",
    "Retenue",
    "Retenue",
    "Non retenue",
    "Non retenue"
  ),
  check.names = FALSE
)

dico_variables <- dico_variables[
  order(dico_variables$Choix != "Retenue", dico_variables[["Nom de la variable"]]),
]

rownames(dico_variables) <- NULL
